Algoritmo "Questão 3"
// 3) Fazer um programa que pergunte um valor em Dólares e apresente
//o equivalente em Reais. Considere U$1,00 =R$1,72.
Var
// Seção de Declarações das variáveis
valor1:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Por favor, informe um valor em dólar:")
  leia(valor1)
  
  escreva("Esse valor equivale a:", valor1*1.72, " reais")

Fimalgoritmo